### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by noguchi-takanori** [noguchi-takanori/furima-36054#9]
URL
https://furima-36054.herokuapp.com/

Basic認証のIDとパスワード
ID:admin
PassWord:NoguchiJapan

出品者用のメールアドレスとパスワード
sell_user@gmail.com
selluser

購入者用のメールアドレスとパスワード
buy_user@gmil.com
buyuser

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **新規登録ページにて、パスワードは、半角英数字混合での入力を必須としましょう**
文字のみ、数字のみの入力で登録ができてしまいます。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@noguchi-takanori さん、修正とご提出ありがとうございます‼︎
動作の確認をしたところ、新たに修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **商品購入ページにて、商品出品時に登録した情報のうち、「商品名・商品画像・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されるよう修正しましょう**
・入力した商品名ではなく「商品名」というテキストが表示されてしまいます。
・価格が正しく表示されていない状態です。
<img width="662" alt="スクリーンショット_2021-11-20_18_11_22" src="https://user-images.githubusercontent.com/54050089/142720949-23bfc72f-4267-4c56-8a48-eeff61f0df3d.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@noguchi-takanori さん、お待たせいたしました。修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM** です✨　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/142745276-61662b4b-6d57-417d-b309-fe826b84cee5.png)
